# Generated by Django 4.2.23 on 2025-08-21 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name='Место выполнения')),
                ('time', models.TimeField(verbose_name='Время выполнения')),
                ('action', models.TextField(verbose_name='Действие привычки')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('periodicity', models.PositiveSmallIntegerField(default=1, verbose_name='Периодичность (в днях)')),
                ('reward', models.TextField(blank=True, null=True, verbose_name='Вознаграждение')),
                ('execution_time', models.PositiveIntegerField(verbose_name='Время на выполнение (в секундах)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_to', to='habits.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['id'],
            },
        ),
    ]
