# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches: [ "develop" ] # Триггер на пуш в ветку develop
  pull_request:
    branches: [ "develop" ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        # Существующие переменные
        DEBUG: True
        SECRET_KEY: not-a-secret-for-ci
        TELEGRAM_BOT_TOKEN: fake-token-for-ci
        TELEGRAM_BOT_USERNAME: fake_bot
        CELERY_BROKER_URL: redis://localhost:6379/0
        CELERY_RESULT_BACKEND: redis://localhost:6379/0
        # НОВЫЕ переменные для тестовой БД
        DB_HOST: localhost
        DB_PORT: 5432
        DB_NAME: postgres
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_ENGINE: django.db.backends.postgresql
      run: |
        python manage.py test

  build:
    needs: test-and-lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build specific service image
      run: docker build -t habit_tracker-web .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/deployer/habit_tracker
          git pull origin develop
          docker-compose down
          docker-compose up -d --build